name: "Trigger GSL Terraform Repository action"

on:
  push:
    branches:
      - 'gsl-**'

jobs:
  GSL_Terraform_PR:
    name: "GSL Terraform PR"
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Trigger gsl terraform repository action
        uses: peter-evans/repository-dispatch@v1
        with:
          repository: delca85/learn-terraform-github-actions
          token: ${{ secrets.REPO_PAT_TOKEN }}
          event-type: push_gsl_branch
          client-payload: '{"branch_name": "${{ steps.extract_branch.outputs.branch }}"}'
